services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mongodb+srv://daniilussuslov:1wdc3waz2wsxA!@cluster0.4vlqg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
    mem_limit: 256m
    mem_reservation: 128m

  # db:
#   image: mongo:5.0.3
#   environment:
#     MONGO_INITDB_ROOT_USERNAME: monty
#     MONGO_INITDB_ROOT_PASSWORD: pass
#   volumes:
#     - ./mongodb-keyfile:/etc/mongo/keyfile
#   command: ["--replSet", "rs0", "--keyFile", "/etc/mongo/keyfile"]





